=== sergio-l-marques-alb/olt-switchsw/lib/broadcom-sdk-xgs/sdk-all-switchdrvr-6.5.15/broadcom/esw_sdk/tools/autocoder/dbal/dnx/field_types/field_types_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:include schemaLocation="../dbal_types_definition.xsd"/>

    <xs:element name="FieldTypesDbCatalog">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="FieldType" maxOccurs="unbounded">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="OneLineDescription" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="FieldDbInterface"  minOccurs="1" maxOccurs="1">
            <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="ChildFields" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ChildField" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attributeGroup ref="FieldAndTableNameAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="EnumValues" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="EnumVal" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attributeGroup ref="EnumValsAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="StructFields" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="StructField" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attributeGroup ref="FieldDefinitionAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="FieldDefines" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Define" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attributeGroup ref="DefineAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
            </xs:complexType>
            </xs:element>
            <xs:element name="FieldToPhyDbMapping"  minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
            <xs:sequence>
                <xs:choice>
				<xs:element name="ReferenceField" type="RefernceFieldType" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="ChildFieldsEncoding" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ChildField" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attributeGroup ref="FieldAndTableNameAttr"/>
                            <xs:attributeGroup ref="FieldEncodeAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="EnumValueMapping" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="EnumVal" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attributeGroup ref="EnumMappingAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="StructFieldsEncoding" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="StructField" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attributeGroup ref="StructFieldEncodingAttr"/>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                </xs:choice>
                <xs:element name="ValueRestricts" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="MinValue" type="FieldTypeRestrictChildAttr" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="MaxValue" type="FieldTypeRestrictChildAttr" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="ConstValue" type="FieldTypeRestrictChildAttr" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="DefaultValue" type="FieldTypeRestrictDefaultValueAttr" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="IllegalValues" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IllegalValue" type="FieldTypeRestrictChildAttr" minOccurs="0" maxOccurs="10"/>
                        </xs:sequence>
                        </xs:complexType>                        
                        </xs:element>                                     
                    </xs:sequence>
                </xs:complexType>
                </xs:element>
                <xs:element name="Encoding" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attributeGroup ref="FieldEncodeAttr"/>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="fieldPhyDbMappingType"/>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
            <xs:attributeGroup ref="FieldTypeDefinitionAttr"/>
        </xs:complexType>
        
            <!-- In Field, all child encoding should be defined in interface and vice-versa -->
            <xs:keyref name="MappingChildKeyRef" refer="MappedChild">
                <xs:selector xpath="FieldToPhyDbMapping/ChildFieldsEncoding/ChildField" />
                <xs:field xpath="@Name" />
            </xs:keyref>

            <xs:key name="MappedChild">
                <xs:selector xpath="FieldDbInterface/ChildFields/ChildField" />
                <xs:field xpath="@Name" />
            </xs:key>

            <xs:key name="ChildList">
                <xs:selector xpath="FieldToPhyDbMapping/ChildFieldsEncoding/ChildField" />
                <xs:field xpath="@Name" />
            </xs:key>

            <xs:unique name="UniqueChildField">
                <xs:selector xpath="FieldDbInterface/ChildFields/ChildField"/>
                <xs:field xpath="@Name"/>
            </xs:unique>

            <xs:unique name="UniqueChildEncoded">
                <xs:selector xpath="FieldToPhyDbMapping/ChildFieldsEncoding/ChildField"/>
                <xs:field xpath="@Name"/>
            </xs:unique>

            </xs:element>
    </xs:sequence>
    </xs:complexType>

        <xs:unique name="UniqueField">
            <xs:selector xpath="FieldType"/>
            <xs:field xpath="@Name"/>
        </xs:unique>

    </xs:element>
    
</xs:schema>

=== sergio-l-marques-alb/olt-switchsw/lib/broadcom-sdk-xgs/sdk-all-switchdrvr-6.5.18/broadcom/esw_sdk/tools/autocoder/dbal/dnx/field_types/auto_generated/standard_1/standard_1_virtual_tcam_field_types.xml
<?xml version="1.0" encoding="UTF-8"?>

<FieldTypesDbCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../field_types_schema.xsd">

    <GeneralInfo image="standard_1" dynamic_loading="0" />

<FieldType Name="PRTTCAM_KEY_VP_COE" Print="STRUCTURE" Size="14">
    <OneLineDescription>PRT Virtual for CoE</OneLineDescription>
    <FieldDbInterface>
        <StructFields>
            <StructField Name="VID" Size="8" Type="VLAN_ID"/>
            <StructField Name="PTC_ATTRIBUTE" Size="6" Type="UINT"/>
        </StructFields>
    </FieldDbInterface>
    <FieldToPhyDbMapping/>
</FieldType>


<FieldType Name="PRTTCAM_KEY_VP_PON" Print="STRUCTURE" Size="13">
    <OneLineDescription>PON</OneLineDescription>
    <FieldDbInterface>
        <StructFields>
            <StructField Name="PON_TAG_PON_SUBPORT_ID" Size="3" Type="UINT"/>
            <StructField Name="PTC" Size="DNX_DATA.mdb_app_db.fields.numeric_mdb_field___217"/>
            <StructField Name="ZERO_PADDING" Size="DNX_DATA.mdb_app_db.fields.numeric_mdb_field___218"/>
        </StructFields>
    </FieldDbInterface>
    <FieldToPhyDbMapping/>
</FieldType>


<FieldType Name="PRTTCAM_KEY_VP_SPA" Print="STRUCTURE" Size="16">
    <OneLineDescription>PRT Virtual for SPA</OneLineDescription>
    <FieldDbInterface>
        <StructFields>
            <StructField Name="SYSTEM_PORT_AGGREGATE" Size="16" Type="SYSTEM_PORT"/>
        </StructFields>
    </FieldDbInterface>
    <FieldToPhyDbMapping/>
</FieldType>


<FieldType Name="PRT_KBR_INFO_HALF" Print="UINT32" Size="17">
    <OneLineDescription/>
    <FieldDbInterface>
        <ChildFields>
            <ChildField Name="PRTTCAM_KEY_VP_COE"/>
            <ChildField Name="PRTTCAM_KEY_VP_PON"/>
            <ChildField Name="PRTTCAM_KEY_VP_SPA"/>
        </ChildFields>
    </FieldDbInterface>
    <FieldToPhyDbMapping>
        <ChildFieldsEncoding>
            <ChildField EncodeType="PREFIX" Name="PRTTCAM_KEY_VP_COE" Value="4"/>
            <ChildField EncodeType="PREFIX" Name="PRTTCAM_KEY_VP_PON" Value="10"/>
            <ChildField EncodeType="PREFIX" Name="PRTTCAM_KEY_VP_SPA" Value="0"/>
        </ChildFieldsEncoding>
    </FieldToPhyDbMapping>
</FieldType>

</FieldTypesDbCatalog>
